bored/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('bored_app.urls')),
    path('admin/', admin.site.urls),
]

bored_app/urls.py
from django.urls import path
from . import views

app_name = 'bored_app'
urlpatterns = [
    path('', views.homePage, name="home"),
]

bored_app/models.py
from django.db import models


class SearchHistory(models.Model):
    activity = models.CharField(max_length=300)
    activity_type = models.CharField(max_length=100)
    activity_key = models.CharField(max_length=10)
    search_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.activity

bored_app/views.py
from django.shortcuts import render
import requests
from .models import SearchHistory


def homePage(request):
    template_name = 'homePage.html'

    if (request.method == 'POST'):
        select = request.POST['select']
        select_list = ["education", "recreational", "social", "diy",
                       "charity", "cooking", "relaxation", "music", "busywork"]
        if not select in select_list:
            select = "random"

        url = 'https://www.boredapi.com/api/activity/' if select == 'random' else 'https://www.boredapi.com/api/activity/' + \
            '?type={}'.format(select)

        res = requests.get(url).json()

        search = SearchHistory.objects.create(
            activity=res['activity'],
            activity_type=res['type'],
            activity_key=res['key'],
        )

        data = {
            'res': res
        }
        return render(request, template_name, data)
    return render(request, template_name)

bored_app/templates/card.html
{% load static %}
{% block style %}  <link href="{% static 'card.css' %}" rel="stylesheet" /> {% endblock style %}


	<div class="row course justify-content-center">
		<div class="col-12 course-info">
            <div class="row">
                <div class="col-6">
                    <h6>Activity:</h6>
                </div>
                <div class="col-6 text-right">
                    {% if res.link %}
                        <h6>Link: <a href="{{res.link}}" target="_blank">Read more</a></h6>
                    {% else %}
                        <h6>Link: <a href="#">none</a></h6>
                    {% endif %}
                </div>
            </div>
			<h2 class="text-center">{{res.activity}}</h2>
            <hr>
            <div class="row">
            
                <div class="col-4 text-center">
                    <h3 class="font-size-14">Type:</h3>
                    <hr>
                    <span class="value text-capitalize">{{res.type}}</span>
                </div>
                <div class="col-4 text-center">
                    <h3 class="font-size-14">Accessibility:</h3>
                    <hr>
                    <span class="value">{{res.accessibility}}</span>

                </div>
                <div class="col-4 text-center">
                    <h3 class="font-size-14">Participants:</h3>  
                    <hr>
                    <span class="value">{{res.participants}}</span>
                </div>
		    </div>
		</div>
	</div>
    <div class="row justify-content-center">
        <div class="col-12 p-20">
            <h3 class="">Hint:</h3>
            <p class="hint-text"><span class="font-weight-bold">Link:</span> A link for read more about the activity [none, link]</p>
            <p class="hint-text"><span class="font-weight-bold">Participants:</span> The number of people that this activity could involve [0, n]</p>
            <p class="hint-text"><span class="font-weight-bold">Accessibility:</span> A factor describing how possible an event is to do with zero being the most accessible [0.0, 1.0]</p>
        </div>
    </div>
    

bored_app/templates/homePage.html
{% extends 'base.html' %}{% load static %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6 col-md-12 text-center">
                <p class="home-title text-muted">Do You Feel Bored?</p>
                <p class="home-text"> — Let's find you something to do — </p>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-12 justify-content-center">
                <form class="form pb-10" id="form" method="POST" action="{% url 'bored_app:home' %}">
                    {% csrf_token %}
                    <div class="row my-15 justify-content-center">

                        <div class="form-group col-lg-6 col-10 m-5">
                            <select name="select" class="form-control" id="select">
                                <option value="" selected="selected" disabled="disabled">Select Type Of The Activity</option>
                                <option value="random">Random</option>
                                <option value="education">Education</option>
                                <option value="recreational">Recreational</option>
                                <option value="social">social</option>
                                <option value="diy">diy</option>
                                <option value="charity">charity</option>
                                <option value="cooking">cooking</option>
                                <option value="relaxation">relaxation</option>
                                <option value="music">music</option>
                                <option value="busywork">busywork</option>
                            </select>
                        </div>  

                        
                    </div>
                </form>
            </div>
        </div>
        {% if res %}
        <div class="row justify-content-center">
            {% include 'card.html' %}
        </div>
        {% else %}
            <div class="row justify-content-center">
                <div class="col-lg-6 col-md-12 text-center">
                    <img src="{% static 'bored.svg' %}" width=60%>
                </div>
            </div>   
        {% endif %}
    </div>

{% endblock content %}

templates/base.html
<!DOCTYPE html> {% load static %}
<html>
<head>
  <!-- Meta tags -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" />
  <meta name="viewport" content="width=device-width" />


  <title>{% block title %}Bored{% endblock title %}</title>

  <!-- Icons -->
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

  <!-- Halfmoon CSS -->
  <link href="{% static 'halfmoon/halfmoon.min.css' %}" rel="stylesheet" />
  <link href="{% static 'app.css' %}" rel="stylesheet" />

</head>
<body data-set-preferred-theme-onload="true">
  	<!-- Page wrapper with navbar, sidebar, and navbar fixed bottom -->
  	<div class="page-wrapper with-navbar with-navbar-fixed-bottom">

		<!-- Navbar -->
		<nav class="navbar">
			<a href="/" class="navbar-brand ml-10 ml-sm-20">
				Bored
			</a>
			<div class="navbar-content ml-auto">
				<button class="btn btn-action mr-5" type="button" onclick="halfmoon.toggleDarkMode()" aria-label="Toggle dark mode">
						<i class="fa fa-moon" aria-hidden="true"></i>
				</button>
				<a href="https://github.com/abdlalisalmi/DJANGO-Bored" target="_blank" class="btn" role="button"><i class="fab fa-github"></i></a>
			</div>
		</nav>

		<!-- Content wrapper -->
		<div class="content-wrapper">
			{% block content %}
			{% endblock content %}
		</div>

		<!-- Navbar fixed bottom -->
		<nav class="navbar navbar-fixed-bottom">
			<ul class="navbar-nav ml-auto"> <!-- ml-auto = margin-left: auto -->
				<li class="nav-item">
					<a href="https://github.com/abdlalisalmi" class="nav-link" target="_blank">Github</a>
				</li>
				<li class="nav-item">
					<a href="https://www.boredapi.com/documentation" target="_blank" class="nav-link">API</a>
				</li>
			</ul>
			<!-- Navbar text -->
			<span class="navbar-text">
				&copy; Bored
			</span>
      	</nav>

  	</div>

	<!-- Halfmoon JS -->
	<script src="{% static 'halfmoon/halfmoon.min.js' %}"></script>
	<script src="{% static 'app.js' %}"></script>
	{% block script %} {% endblock script %}
</body>
</html>